version: '3.7'

services:

  interface:
    build:
      context: ./interface
      dockerfile: Dockerfile
    volumes:
      - ./interface:/app
    ports:
      - '8080:8080'
    environment:
      - CHOKIDAR_USEPOLLING=true