version: '3'

services:

  interface:
    build:
      context: ./interface
      dockerfile: Dockerfile
    volumes:
      - ./interface:/app
    ports:
      - '8080:8080'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VUE_APP_API_URL=${VUE_APP_API_URL}

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - VIDEO_QUALITY=${VIDEO_QUALITY}
    depends_on:
      - redis
  redis:
      image: redis